/* eslint-disable import/no-anonymous-default-export */
import {
  STUDENTS_COLUMNS,
  STUDENTS_COLUMN,
  studentExamsReportColumns,
  studentFeesReportColumns,
  LEVEL_OPTIONS,
  LEVEL_TYPE_OPTIONS,
  STUDENTS_EXAMS_COLUMN,
  STUDENTS_ATTENDANCE_COLUMNS,
} from "./studentColumns";
import { TEACHERS_COLUMN } from "./teacherColumn";
import {
  SCHOOL_SESSION_COLUMN,
  SCHOOL_TERMS,
  SCHOOL_LEVELS,
  SUBJECT_OPTIONS,
  SCHOOl_SUBJECTS,
  FEES_OPTIONS,
  FEES_COLUMNS,
  SCHOOL_FEES_COLUMNS,
  MESSAGE_COLUMNS,
  EXAMS_COLUMNS,
  STUDENT_FEES_HISTORY_COLUMNS,
  USERS_COLUMNS,
} from "./sessionColums";

export default {
  USERS_COLUMNS,
  //
  STUDENTS_COLUMNS,
  STUDENTS_COLUMN,
  STUDENTS_EXAMS_COLUMN,
  STUDENTS_ATTENDANCE_COLUMNS,
  studentExamsReportColumns,
  studentFeesReportColumns,

  //
  SCHOOL_SESSION_COLUMN,
  SCHOOL_LEVELS,

  //
  SCHOOL_TERMS,
  LEVEL_OPTIONS,
  LEVEL_TYPE_OPTIONS,
  //
  SUBJECT_OPTIONS,
  SCHOOl_SUBJECTS,
  //
  FEES_OPTIONS,
  FEES_COLUMNS,
  SCHOOL_FEES_COLUMNS,
  STUDENT_FEES_HISTORY_COLUMNS,

  //Teacher
  TEACHERS_COLUMN,

  //Message
  MESSAGE_COLUMNS,

  //exams
  EXAMS_COLUMNS,
};
