
export const TEACHERSREMARKS = [
  "Quite impressive, keep it up.",
  "An outstanding result, do not rest on your oars.",
  "shows interest and enthusiasm for study.",
  "An excellent result, keep it up.",
  "Is a very brilliant and clever student in the class.",
  "Is such a pleasure to have great students like you in our class.",
  "Asks questions when needed. ",
  "Always ready for more challenges that is something I like the most about you.",
  "Is one of the hardworking students in our class. ",
  "Such a trustworthy and caring  in the class.",
  "I love that he takes time to think before he speaks.",
  "He is quite active in extracurricular activities. ",
  "Works very well when in the team or with his best friends. ",
  "So far, you progress is consistent. ",
  "Enthusiast to learn and try something new.",
  "Completes every assignment and task on time. ",
  "I like your enthusiasm to learn new things. That’s a great skill you got. ",
  "Your performance this time is truly impressive. Do you mind sharing how many hours you study at home everyday?",
  "Very hardworking and supportive students in our class. We’re lucky to have you.",
  "So much surprised by his transformations.  Great!",
  "This school is so proud to have smart kids like you.Agem among us.",
  "Very brilliant and clever student of the class.",
  "Such a pleasure to have great students like you in our class.",
  "Is a sincere and dedicated student who always helps others.",
  "Leads a team very well, and quite a great manager for group activities.",
  "Having great potential and getting his tasks finished on time.",
  "Is positive, confident, and very supportive to others. ",
  "Completes every assigned work on time, with a great focus. ",
  " practicing a lot at home, I think. Impressive performance so far. ",
  "Such a great student that others might have a lot to learn from. ",
  "Seems like you are born with leadership skills, very active, and managed. ",
  "Spends time thinking and choosing the right words to respond. ",
  "Learns things a lot faster and remembers them for a longer period. ",
  "Very confident and speaks very well in front of the whole class. ",
  "Have an interest in learning something new and be present while teaching. ",
  "Successfully passing the training phase, now it’s time to level up.",
  "Keep hustling you will achieve it soon.",

];

export const INTEREST = [
  "Has a well-developed sense of humor.",
  "Holds many varied interests.",
  "Has a keen interest that has been shared with the class.",
  "Displays and talks about personal items from home when they relate to topics of study.",
  "Provides background knowledge about topics of particular interest to them.",
  "Has an impressive understanding and depth of knowledge about their interests.",
  "Seeks additional information independently about classroom topics that pique interest.",
  "Reads extensively for enjoyment.",
  "Frequently discusses concepts about which they have read.",
  "Is a gifted performer.",
  "Is a talented artist.",
  "Is a flair for dramatic reading and acting.",
  "Enjoys sharing their musical talent with the class.",
  "Discusses ideas that they’ve read regularly.",
  "Enjoys showing off their musical abilities to the rest of the class.",
  "Reads every day for pleasure.",
  "Has a firm grasp of their interests.",
  "Has a neat hobby that they shared with the rest of the class.",
  "Has a wide range of interests.",
  "Independently seeks out additional information on classroom topics.",
  "Is a fantastic performer.",
  "Is a gifted musician.",
  "possesses a witty sense of humor.",
];

export const CONDUCT = [
  "is an enthusiastic learner who seems to enjoy school.",
  "exhibits a positive outlook and attitude in the classroom.",
  "appears well rested and ready for each day's activities.",
  "shows enthusiasm for classroom activities.",
  "shows initiative and looks for new ways to get involved.",
  "uses instincts to deal with matters independently and in a positive way.",
  "strives to reach their full potential.",
  "is committed to doing their best.",
  "seeks new challenges.",
  "takes responsibility for their learning.",
  "cooperates consistently with the teacher and other students.",
  "transitions easily between classroom activities without distraction.",
  "is courteous and shows good manners in the classroom.",
  "follows classroom rules.",
  "conducts themselves with maturity.",
  "responds appropriately when corrected.",
  "remains focused on the activity at hand.",
  "resists the urge to be distracted by other students.",
  "is kind and helpful to everyone in the classroom.",
  "sets an example of excellence in behavior and cooperation.",
  "shows respect for teachers and peers.",
  "treats school property and the belongings of others with care and respect.",
  "is honest and trustworthy in dealings with others.",
  "displays good citizenship by assisting other students.",
  "joins in school community projects.",
  "is concerned about the feelings of peers.",
  "faithfully performs classroom tasks.",
  "can be depended on to do what they are asked to do.",
  "seeks responsibilities and follows through.",
  "is thoughtful in interactions with others.",
  "is kind, respectful and helpful when interacting with peers",
  "is respectful of other students in our classroom and the school community",
  "demonstrates responsibility daily by caring for the materials in our classroom carefully and thoughtfully",
  "takes  classroom jobs seriously and demonstrates responsibility when completing them",
  "is always honest and can be counted on to recount information when asked",
  "is considerate when interacting with  teachers",
  "demonstrates manners on a daily basis and is always respectful",
  "has incredible self-discipline and always gets work done in a timely manner",
  "can be counted on to be one of the first students to begin working on the task that is given",
  "perseveres when faced with difficulty by asking questions and trying best",
  "does not give up when facing a task that is difficult and always does best",
  "is such a caring and demonstrates concern for peers",
  "demonstrates caring nature when helping peers when they need the assistance",
  "is a model citizen in our classroom",
  "is demonstrates citizenship in our classroom by helping to keep it clean and taking care of the materials in it",
  "can always be counted on to cooperate with peers",
  "is able to cooperate and work well with any of the other students in the class",
  "is exceptionally organized and takes care of things",
  "is always enthusiastic when completing work",
  "is agreeable and polite when working with others",
  "is thoughtful and kind in interactions with others",
  "is creative when problem solving",
  "is very hardworking and always completes all of work",
  "is patient and kind when working with peers who need extra assistance",
  "trustworthy and can always be counted on to step in and help where needed",
  // Has a great deal of respect for all visitors to the classroom.
  // 22. Cares for and respects her classmates.
  // 23. Is always respectful to classroom equipment.
  // 24. Always puts her hand up and follows instructions.
  // 25. Is very considerate of others and often puts others’ needs and
  // interests at the front of her mind.
  // 26. Is a very respectful and responsible classmate.
  // 27. Has proven to be a courteous and polite classmate.
  // 28. Is held in high regard for her kindness to others.
];
