const TEACHERSREMARKS = [
  'Quite impressive, keep it up.',
  'An outstanding result, do not rest on your oars.',
  'shows interest and enthusiasm for study.',
  'An excellent result, keep it up.',
  'Is a very brilliant and clever student in the class.',
  'Is such a pleasure to have great students like you in our class.',
  'Asks questions when needed. ',
  'Always ready for more challenges that is something I like the most about you.',
  'Is one of the hardworking students in our class. ',
  'Such a trustworthy and caring  in the class.',
  'I love that he takes time to think before he speaks.',
  'He is quite active in extracurricular activities. ',
  'Works very well when in the team or with his best friends. ',
  'So far, you progress is consistent. ',
  'Enthusiast to learn and try something new.',
  'Completes every assignment and task on time. ',
  'I like your enthusiasm to learn new things. That’s a great skill you got. ',
  'Your performance this time is truly impressive. Do you mind sharing how many hours you study at home everyday?',
  'Very hardworking and supportive students in our class. We’re lucky to have you.',
  'So much surprised by his transformations.  Great!',
  'This school is so proud to have smart kids like you.Agem among us.',
  'Very brilliant and clever student of the class.',
  'Such a pleasure to have great students like you in our class.',
  'Is a sincere and dedicated student who always helps others.',
  'Leads a team very well, and quite a great manager for group activities.',
  'Having great potential and getting his tasks finished on time.',
  'Is positive, confident, and very supportive to others. ',
  'Completes every assigned work on time, with a great focus. ',
  ' practicing a lot at home, I think. Impressive performance so far. ',
  'Such a great student that others might have a lot to learn from. ',
  'Seems like you are born with leadership skills, very active, and managed. ',
  'Spends time thinking and choosing the right words to respond. ',
  'Learns things a lot faster and remembers them for a longer period. ',
  'Very confident and speaks very well in front of the whole class. ',
  'Have an interest in learning something new and be present while teaching. ',
  'Successfully passing the training phase, now it’s time to level up.',
  'Keep hustling you will achieve it soon.',
  'Needs help to increase academic skills, such as reading and writing',
  'Demonstrates a need for consistent effort and motivation, especially in extra curricula activites',
  'Requires help with organizational skills, such as reading and writing',
  'Could benefit from extra classes',
  'Needs to be encouraged to comply with school rules, such as neatness',
  'Could benefit from improving  work habits, such as reading',
  'Needs to be encouraged to listen and pay attention in class',
  'Needs help to understand instructions',
  'Requires repetition to retain information',
  'Needs encouragement to do work on your own',
  'Demonstrates a need for direct supervision to complete work',
  'Needs to be encouraged to work more slowly and accurately',
  'Would benefit from supervision of homework',
  'Requires support to interact with classmates in a positive way',
  'Would benefit from learning self-control skills',
  'Needs to be encouraged to accept responsibility for  errors and misbehavior',
  'Needs to demonstrate improvement in academic work  to gain the fundamentals needed for this grade',
];

const INTEREST = [
  'Has a well-developed sense of humor.',
  'Holds many varied interests.',
  'Has a keen interest that has been shared with the class.',
  'Displays and talks about personal items from home when they relate to topics of study.',
  'Provides background knowledge about topics of particular interest to them.',
  'Has an impressive understanding and depth of knowledge about their interests.',
  'Seeks additional information independently about classroom topics that pique interest.',
  'Reads extensively for enjoyment.',
  'Frequently discusses concepts about which they have read.',
  'Is a gifted performer.',
  'Is a talented artist.',
  'Ias a flair for dramatic reading and acting.',
  'Enjoys sharing their musical talent with the class.',
  'Discusses ideas that they’ve read regularly.',
  'Enjoys showing off their musical abilities to the rest of the class.',
  'Reads every day for pleasure.',
  'Has a firm grasp of their interests.',
  'Has a neat hobby that they shared with the rest of the class.',
  'Has a wide range of interests.',
  'Independently seeks out additional information on classroom topics.',
  'Is a fantastic performer.',
  'Is a gifted musician.',
  'possesses a witty sense of humor.',
];

const CONDUCT = [
  'is an enthusiastic learner who seems to enjoy school.',
  'exhibits a positive outlook and attitude in the classroom.',
  "appears well rested and ready for each day's activities.",
  'shows enthusiasm for classroom activities.',
  'shows initiative and looks for new ways to get involved.',
  'uses instincts to deal with matters independently and in a positive way.',
  'strives to reach their full potential.',
  'is committed to doing their best.',
  'seeks new challenges.',
  'takes responsibility for their learning.',
  'cooperates consistently with the teacher and other students.',
  'transitions easily between classroom activities without distraction.',
  'is courteous and shows good manners in the classroom.',
  'follows classroom rules.',
  'conducts themselves with maturity.',
  'responds appropriately when corrected.',
  'remains focused on the activity at hand.',
  'resists the urge to be distracted by other students.',
  'is kind and helpful to everyone in the classroom.',
  'sets an example of excellence in behavior and cooperation.',
  'shows respect for teachers and peers.',
  'treats school property and the belongings of others with care and respect.',
  'is honest and trustworthy in dealings with others.',
  'displays good citizenship by assisting other students.',
  'joins in school community projects.',
  'is concerned about the feelings of peers.',
  'faithfully performs classroom tasks.',
  'can be depended on to do what they are asked to do.',
  'seeks responsibilities and follows through.',
  'is thoughtful in interactions with others.',
  'is kind, respectful and helpful when interacting with peers',
  'is respectful of other students in our classroom and the school community',
  'demonstrates responsibility daily by caring for the materials in our classroom carefully and thoughtfully',
  'takes  classroom jobs seriously and demonstrates responsibility when completing them',
  'is always honest and can be counted on to recount information when asked',
  'is considerate when interacting with  teachers',
  'demonstrates manners on a daily basis and is always respectful',
  'has incredible self-discipline and always gets work done in a timely manner',
  'can be counted on to be one of the first students to begin working on the task that is given',
  'perseveres when faced with difficulty by asking questions and trying best',
  'does not give up when facing a task that is difficult and always does best',
  'is such a caring and demonstrates concern for peers',
  'demonstrates caring nature when helping peers when they need the assistance',
  'is a model citizen in our classroom',
  'is demonstrates citizenship in our classroom by helping to keep it clean and taking care of the materials in it',
  'can always be counted on to cooperate with peers',
  'is able to cooperate and work well with any of the other students in the class',
  'is exceptionally organized and takes care of things',
  'is always enthusiastic when completing work',
  'is agreeable and polite when working with others',
  'is thoughtful and kind in interactions with others',
  'is creative when problem solving',
  'is very hardworking and always completes all of work',
  'is patient and kind when working with peers who need extra assistance',
  'trustworthy and can always be counted on to step in and help where needed',
];

const EXCELLENT = [
  'Your child exhibits exceptional focus and diligence in their work.',
  'Your student is excellent at taking ownership of their learning.',
  'I appreciate that your child is committed to doing their best.',
  'Your student seeks new challenges.',
  'Your child has a fantastic work ethic.',
  'Your child exceeds expectations on a regular basis.',
  'Your student avoids careless errors through attention to detail.',
  'Your child sets high standards for themself and reaches them.',
  'Teaching your child is always an adventure! I love it.',
  'Your child conducts with maturity.',
  'Your child is able to focus and stays on task during independent work times.',
  'Your student uses instincts to deal with matters independently and in a positive way.',
  'Completes asynchronous and autonomous work and always meets deadlines.',
  'When it comes to completing learning assignments, she goes above and beyond in terms of detail and quality.',
  'With online learning,  has successfully maintained / class demeanour and work habits.',
  'Is fascinated by the nature of learning and always puts in best effort to find the greatest available solutions.',
  'Is a focused and enthusiastic participant in the online learning session, and works with zeal and determination.',
  'Is able to reach full potential, as evidenced by contributions to conversations and work submitted.',
  'Quite impressive, keep it up.',
  'An outstanding result, do not rest on your oars.',
  'Shows interest and enthusiasm for study.',
  'An excellent result, keep it up.',
  'Is a very brilliant and clever student in the class.',
  'Is such a pleasure to have great students like you in our class.',
  'Asks questions when needed. ',
  'Always ready for more challenges that is something I like the most about you.',
  'Is one of the hardworking students in our class. ',
  'Such a trustworthy and caring  in the class.',
  'I love that he takes time to think before he speaks.',
  'He is quite active in extracurricular activities. ',
  'Works very well when in the team with  best friends. ',
  'So far, you progress is consistent. ',
  'Enthusiast to learn and try something new.',
  'Completes every assignment and task on time. ',
  'I like your enthusiasm to learn new things. That’s a great skill you got. ',
  'Your performance t time is truly impressive. Do you mind sharing how many hours you study at home everyday?',
  'Very hardworking and supportive students in our class. We’re lucky to have you.',
  'So much surprised by  transformations.  Great!',
  'The school is so proud to have smart kids like you.Agem among us.',
  'Very brilliant and clever student of the class.',
];

const VERYGOOD = [
  'Maintains focus in online learning despite technological challenges and changes associated with remote learning.',
  'Enthusiastically engages in class discussions and works effectively with peers.',
  'Takes charge of own education and always asks for support when needed.',
  'Always arrives on time for class and is a dedicated student.',
  'Is well-prepared, well-organized, and enthusiastic about making the most of online classes.',
  'Is a dedicated student who participates actively in class.',
  'Takes an active interest in own learning.',
  'Pays closeattention, and makes a concerted effort to avoid distractions that could disrupt the learning process.',
  'Is a person who takes responsibility and accountabilityseriously. ',
  'He she makes sound decisions and is open to newideas.',
  'Gets along well with  peers and values varied viewpoints and experiences.',
  'Is constantly looking for ways to assist in the classroom.',
  'Is dependable and trustworthy, follows instructions well.',
  'In written and verbal communication, is thoughtful, insightful.',
  'When solving problems with students, displays maturity and',
  'Exhibits good communication skills when sharing thoughts and ideas about a certain topic/concept.',
  'Excels at transferring classroom knowledge to real-world and real-life circumstances.',
  'It has been a delight having such energy, optimism, and maturity in my class.',
  'Is a classmate who is eager about learning and willing to try new things.',
  'During class, is focused and willing to provide ideas.',
  'With confidence and determination,  completes solo work.',
  'Is a self-starter who takes pride in  job.',
  'In class, is attentive and eager to engage in discussions.',
  'Is a very conscientious worker who puts in a lot of effort and attention on a daily basis.',
  'In  daily labour, makes a willing and conscientious effort.',
  'Makes a conscious effort to study new things and improve on knowledge.',
  'Has done an outstanding job confronting and overcoming significant obstacles. ',
  'When given instructions,takes responsibility and follows them  well',

  //////
];
const AVERAGE = [
  'Is consistently improving.',
  'Is developing very well for  age.',
  'Has shown strong signs of growth in all learning areas.',
  'Has made clear and commendable gains.',
  'Improves each and every day.',
  'hard work and effort has paid off,',
  'Is always willing to listen to instructions.',
  'Is a very helpful and respectful student.',
  'Never misbehaves in class.',
  'Sets a good standard for classmates to follow.',
  'Is very good at following the rules.',
  'has a lot of potential and is working hard to realise it.',
  'Your child is performing to the best of   ability.',
  'Your child is a dependable and conscientious worker.',
  'Your child is enthusiastic about   job in general.',
  'Your child is a dedicated student.',
  'Your child is very conscientious.',
  'Your child is a pleasant and responsible student.',
  'Your child is a dedicated worker.',
  'During the  period,your child is a hard worker.',
  'Your ward is a respectful and conscientious student.',
  'Such a pleasure to have great students like you in our class.',
  'Is a sincere and dedicated student who always helps others.',
  'Leads a team very well, and quite a great manager for group activities.',
  'Having great potential and getting  tasks finished on time.',
  'Is positive, confident, and very supportive to others. ',
  'Completes every assigned work on time, with a great focus. ',
  'practicing a lot at home, I think. Impressive performance so far. ',
  'Such a great student that others might have a lot to learn from. ',
  'Seems like you are born with leadership skills, very active, and managed. ',
  'Spends time thinking and choosing the right words to respond. ',
  'Learns things a lot faster and remembers them for a longer period. ',
  'Very confident and speaks very well in front of the whole class. ',
  'Have an interest in learning something new and be present while teaching. ',
  'Successfully passing the training phase, now it’s time to level up.',
  'Keep hustling you will achieve it soon.',
  'has trouble keeping on task and finishing rassignment.',
  'He she must pay close attention to directions in order to learn to operate autonomously.',
  'Turns in incomplete work no homework on a regular basis.',
  'Encouraging  to complete  work on time and according to the timetable and timeline set.',
  'Does not actively participate in group activities; tefore, is',
  'Encouraged to put forth effort in order to improve communicationskills as well as attention and confidence.',
  'Participates enthusiastically in online group activities, but finds it difficult to work independently',
  'Is a person who takes responsibility and accountability',
  'seriously. He she makes sound decisions and is open to new ideas.',
  'gets along well with  peers and values varied viewpoints and experiences.',
  'is constantly looking for ways to assist in the classroom.',
  'is dependable and trustworthy, follows instructions well, and keeps promises to himself and others.',
  'Has a talent for clearly conveying ideas.',
  'When solving problems with students, displays maturity and exhibits good communication skills when sharing thoughts',
  'excels at transferring classroom knowledge to real-world and real-life circumstances.',
  "It's been a delight having 's energy, optimism, and maturity in my class.",
  'is a classmate who is eager about learning and willing to try new things.',
  'During class,  is focused and willing to provide ideas.',
  'With confidence and determination,  completes solo work.',
  'is a self-starter who takes pride in  job.',
  'In class,  is attentive and eager to engage in discussions.',
  'is a very conscientious worker who puts in a lot of effort and attention on a daily basis.',
  'In  daily labour,  makes a willing and conscientious effort.',
  'makes a conscious effort to study new things and improve',
];
const PASS = [
  'During class engagement and behaviour are inconsistent and disengaged.',
  'is having trouble grasping concepts. It would be useful to pay',
  'more attention to the required tasks and to attend the online classes on a regular basis.',
  'When it comes to schoolwork,  needs a lot of help from adults.',
  'She has trouble grasping simple concepts and is unable to work on  own.',
  'In the online learning environment,  struggled to engage and',
  'participate in discussions and activities.',
  'has not worked hard enough to satisfy the grade level',
  'objectives. It would be great to have regular work habits, active',
  'engagement, and the ability to clarify doubts.',
  'needs to pay greater attention to guidance throughout lessons',
  'in order to apply concepts learned and complete given assignments.',
  'would benefit from demonstrating a stronger desire to participate in class discussions.',
  'needs to be reminded to pay attention during instructions and lessons on a regular basis.',
  'has trouble focusing in class, which hinders   ability to',
  'participate fully in class activities and tasks.',
  'is encouraged to make good use of time in order to finish things on schedule.',
  'is encouraged to take greater responsibility for completing',
  'chores without the need for frequent reminders.',
  'must demonstrate that he she is engaged in the learning process through the quality of  work and the efficient use of class time.',
  'Needs to work on focus and concentration during class time.',
  'Has improved in some areas, but continues to slip behind in others.',
  'Is showing some lack of focus and is slipping behind in some subjects.',
  'Te is still a lot of room for growth and we are working on',
  'improving  focus and drive in coming months.',
  'It would be great to see some improvement in  weakest subjects in the future.',
  'I would like to see  asking for help when stuck on tasks',
  'Needs help to increase academic skills, such as reading and writing',
  'Demonstrates a need for consistent effort and motivation, especially in extra curricula activites',
  'Requires help with organizational skills, such as reading and writing',
  'Could benefit from extra classes',
  'Needs to be encouraged to comply with school rules, such as neatness',
  'Could benefit from improving  work habits, such as reading',
  'Needs to be encouraged to listen and pay attention in class',
  'Needs help to understand instructions',
  'Requires repetition to retain information',
  'Needs encouragement to do work on your own',
  'Demonstrates a need for direct supervision to complete work',
  'Needs to be encouraged to work more slowly and accurately',
  'Would benefit from supervision of homework',
  'Requires support to interact with classmates in a positive way',
  'Would benefit from learning self-control skills',
  'Needs to be encouraged to accept responsibility for  errors and misbehavior',
  'Needs to demonstrate improvement in academic work  to gain the fundamentals needed for t grade',
  'Could be getting hig grades if she edited  work more carefully before submission.',
  'Will sometimes make mistakes due to distractedness and carelessness.',
  'Has started to let carelessness seep into  work for the past fewmonths.',
  'Often does not pay enough attention to test questions, leading to small unforced errors.',
];

const FAIL = [
  'Occasionally needs special assistance to stay on task.',
  'Requires some coaxing to complete tasks.',
  'Is at times distracted uninterested in learning.',
  'Is working on paying more attention to  tasks.',
  'Has some off days we she is uninterested in learning.',
  'Is easily distracted by friends.',
  'Needs help to increase academic skills, such as reading and writing',
  'Demonstrates a need for consistent effort and motivation, especially in extra curricula activites',
  'Requires help with organizational skills, such as reading and writing',
  'Could benefit from extra classes',
  'Needs to be encouraged to comply with school rules, such as neatness',
  'Could benefit from improving  work habits, such as reading',
  'Needs to be encouraged to listen and pay attention in class',
  'Needs help to understand instructions',
  'Requires repetition to retain information',
  'Needs encouragement to do work on your own',
  'Demonstrates a need for direct supervision to complete work',
  'Needs to be encouraged to work more slowly and accurately',
  'Would benefit from supervision of homework',
  'Requires support to interact with classmates in a positive way',
  'Would benefit from learning self-control skills',
  'Needs to be encouraged to accept responsibility for  errors and misbehavior',
  'Needs to demonstrate improvement in academic work  to gain the fundamentals needed for t grade',
  'Sometimes struggles to engage in class discussions.',
  'Requires a lot of external rewards to get focused.',
  'Works well below  capabilities due to lack of motivation to do best.',
  'Relies heavily on extrinsic motivation. It would be great to see more intrinsic desire to succeed in coming months.',
  'Struggles to find things she is interested in.',
  'Has trouble getting engaged and interested in class topics.',
  'Will respond well to rewards but struggles to use initiative.',
  'Needs to dig deep and find greater motivation to learn in coming months.',
  'often skip assigned homework tasks.',
  'Regularly forgets to bring homework to school.',
  'Homework is often brought to class incomplete and rushed.',
  'Is often seen completing homework tasks the morning before they are due.',
  'I would like to see  working on setting aside more time for homework in the coming months.',
  'Is good at class work, but needs more initiative to complete weekly homework in a timely manner.',
];

module.exports = {
  CONDUCT,
  INTEREST,
  EXCELLENT,
  VERYGOOD,
  AVERAGE,
  PASS,
  FAIL,
};
